import { CleanTask } from "./types";

export const cleanTasks: CleanTask[] = [
  {
    id: "1",
    property: "Sacarat V1",
    propertyColor: "bg-blue-100 text-blue-700",
    guestName: "Watson → check-in 14:00",
    cleanType: "Pre-Arrival Clean",
    status: "In Progress",
    assignedTeam: "Team A",
    scheduledAt: "Today, 10:00",
    checkInAt: "14:00",
  },
  {
    id: "2",
    property: "Sacarat V2",
    propertyColor: "bg-purple-100 text-purple-700",
    guestName: "Kowalski → departure",
    cleanType: "Departure Clean",
    status: "Scheduled",
    assignedTeam: "Team B",
    scheduledAt: "Today, 11:00",
  },
  {
    id: "3",
    property: "Bophut Villa",
    propertyColor: "bg-green-100 text-green-700",
    guestName: "Delacroix — checked out",
    cleanType: "Departure Clean",
    status: "Completed",
    assignedTeam: "Team C",
    scheduledAt: "Today, 09:00",
  },
  {
    id: "4",
    property: "Sacarat V1",
    propertyColor: "bg-blue-100 text-blue-700",
    guestName: "Garcia stayover",
    cleanType: "Stayover Clean",
    status: "Scheduled",
    assignedTeam: "Team A",
    scheduledAt: "Today, 13:00",
  },
  {
    id: "5",
    property: "Sacarat V2",
    propertyColor: "bg-purple-100 text-purple-700",
    guestName: "Miller stayover",
    cleanType: "Deep Clean",
    status: "Scheduled",
    assignedTeam: "Team B",
    scheduledAt: "Tomorrow, 09:00",
  },
  {
    id: "6",
    property: "Bophut Villa",
    propertyColor: "bg-green-100 text-green-700",
    guestName: "Anderson stayover",
    cleanType: "Stayover Clean",
    status: "Completed",
    assignedTeam: "Team D",
    scheduledAt: "Yesterday, 10:00",
  },
];
