import { Ticket } from "./types";

export const tickets: Ticket[] = [
  // REPORTED
  {
    id: "1",
    property: "Sacarat V2",
    propertyColor: "bg-purple-100 text-purple-700",
    priority: "CRITICAL",
    status: "Reported",
    title: "Master Bedroom A/C Leaking",
    description: "Reported 2h ago · Guest complaint",
    vendor: "Samui AirCon Pros",
    vendorStatus: "Unconfirmed",
    estimatedCost: 3500,
  },
  {
    id: "2",
    property: "Bophut Villa",
    propertyColor: "bg-green-100 text-green-700",
    priority: "LOW",
    status: "Reported",
    title: "Garden Path Lights Out (x3)",
    description: "Reported yesterday · Staff walkthrough",
    vendor: "Island Electrical",
    vendorStatus: "Unconfirmed",
    estimatedCost: 800,
  },
  // SCHEDULED
  {
    id: "3",
    property: "Sacarat V2",
    propertyColor: "bg-purple-100 text-purple-700",
    priority: "MODERATE",
    status: "Scheduled",
    title: "Pool Pump Low Pressure",
    scheduledAt: "Mar 1 · 09:00",
    vendor: "Thai Pool Tech",
    vendorStatus: "Confirmed",
    estimatedCost: 2200,
  },
  {
    id: "4",
    property: "Sacarat V1",
    propertyColor: "bg-blue-100 text-blue-700",
    priority: "CRITICAL",
    status: "Scheduled",
    title: "Hot Water Heater Failure",
    scheduledAt: "Vendor en route — ETA 30 min",
    vendor: "Koh Samui Plumbing",
    vendorStatus: "En Route",
    estimatedCost: 4500,
  },
  // AWAITING
  {
    id: "5",
    property: "Sacarat V1",
    propertyColor: "bg-blue-100 text-blue-700",
    priority: "MODERATE",
    status: "Awaiting",
    title: "Roof Tiles Cracked (2 pcs)",
    partsInfo: "Parts on order — ETA Mar 5",
    vendor: "Somchai (handyman)",
    vendorStatus: "Waiting",
    estimatedCost: 1800,
    openedAt: "Feb 20",
  },
  // RESOLVED
  {
    id: "6",
    property: "Sacarat V2",
    propertyColor: "bg-purple-100 text-purple-700",
    priority: "MODERATE",
    status: "Resolved",
    title: "Bathroom Exhaust Fan Replaced",
    completedAt: "Feb 25",
    timeOnSite: "1h on site",
    vendor: "Island Electrical",
    loggedCost: 2200,
    hasReceipt: true,
  },
  {
    id: "7",
    property: "Bophut Villa",
    propertyColor: "bg-green-100 text-green-700",
    priority: "LOW",
    status: "Resolved",
    title: "Front Gate Hinge Repair",
    completedAt: "Feb 26",
    timeOnSite: "30 min",
    vendor: "Somchai (handyman)",
    loggedCost: 500,
    hasReceipt: true,
  },
];
